import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { kassieBaseUrl, knowledgeTerms } from "../../kassie/content";

type Props = { params: Promise<{ term: string }> };
export function generateStaticParams() { return knowledgeTerms.map((t) => ({ term: t.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { term } = await params;
  const item = knowledgeTerms.find((t) => t.slug === term);
  return item ? { title: `${item.title}: betekenis voor ZZP'ers | Kassie`, description: item.summary, alternates: { canonical: `${kassieBaseUrl}/kennisbank/${item.slug}` }, openGraph: { title: `${item.title}: betekenis voor ZZP'ers | Kassie`, description: item.summary, url: `${kassieBaseUrl}/kennisbank/${item.slug}` } } : {};
}

export default async function Page({ params }: Props) {
  const { term } = await params;
  const item = knowledgeTerms.find((t) => t.slug === term);
  if (!item) notFound();
  const url = `${kassieBaseUrl}/kennisbank/${item.slug}`;
  const schema = [{ "@context": "https://schema.org", "@type": "DefinedTerm", name: item.title, description: item.summary, inDefinedTermSet: `${kassieBaseUrl}/kennisbank`, url }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: `Wat is ${item.title}?`, acceptedAnswer: { "@type": "Answer", text: item.summary } }, { "@type": "Question", name: `Waarom is ${item.title} belangrijk voor ZZP'ers?`, acceptedAnswer: { "@type": "Answer", text: `Omdat ${item.title.toLowerCase()} invloed kan hebben op bewijs, facturatie, btw of controleerbaarheid van je administratie.` } }] }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Kassie", item: kassieBaseUrl }, { "@type": "ListItem", position: 2, name: "Kennisbank", item: `${kassieBaseUrl}/kennisbank/${item.slug}` }] }];
  return <main className="kassie-seo-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><section className="kassie-seo-hero"><p className="eyebrow">Kennisbank · peildatum juni 2026</p><h1>{item.title}</h1><p className="lead">{item.summary}</p></section><section className="kassie-seo-content"><article className="kassie-card"><h2>Kort antwoord</h2><p>{item.summary}</p><p>Voor ZZP'ers is vooral belangrijk dat je bewijs, context en datum vastlegt. Kassie helpt om losse administratie-acties reviewbaar te maken.</p></article><article className="kassie-card"><h2>Waarom dit telt voor je administratie</h2><p>{item.title} raakt vaak aan facturen, btw, bewijs, betaalstatus of boekhoudcontrole. Als informatie verspreid staat over mail, WhatsApp, downloads en foto's, wordt controle later moeilijker.</p><p>Leg daarom vast: datum, bedrag, leverancier of klant, zakelijk doel, periode en of je boekhouder nog iets moet beoordelen.</p></article><article className="kassie-card"><h2>Voorbeeld uit de praktijk</h2><p>Stel dat je als ZZP'er een factuur, bon of klantafspraak verwerkt. Dan wil je niet alleen het bedrag bewaren, maar ook waarom het bij deze periode, klant of aangifte hoort. Dat maakt het verschil tussen losse data en een controleerbare administratie.</p></article><article className="kassie-card"><h2>Veelgemaakte fout</h2><p>Veel ondernemers bewaren informatie verspreid over mail, WhatsApp, downloads en foto's. Daardoor wordt controleren lastig. Zet bewijs direct bij je administratie en label twijfelgevallen.</p></article><article className="kassie-card"><h2>Wanneer boekhouder vragen?</h2><p>Vraag beoordeling bij fiscale twijfel, buitenlandse btw, KOR, correcties over eerdere periodes, grote bedragen of gemengd privé/zakelijk gebruik.</p></article><article className="kassie-card"><h2>Verder lezen</h2><ul><li><a href="/boekhouden-zzp">Boekhouden voor ZZP'ers</a></li><li><a href="/btw-aangifte-zzp">BTW-aangifte doen</a></li><li><a href="/factureren-zzp">Factureren als ZZP'er</a></li><li><a href="/bonnen-bewaren-zzp">Bonnen bewaren</a></li></ul></article></section></main>;
}
